# Generated by Django 4.1.7 on 2023-03-25 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.CharField(max_length=5, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(default='', max_length=63)),
                ('week', models.IntegerField(default=1)),
            ],
            options={
                'ordering': ['week', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False, unique=True)),
                ('level', models.IntegerField(default=0)),
                ('num', models.IntegerField(default=0)),
                ('teams', models.TextField(default='')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='index.event')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False, unique=True)),
                ('num', models.IntegerField(default=0)),
                ('name', models.CharField(default='', max_length=60)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.event')),
            ],
        ),
        migrations.CreateModel(
            name='SystemScoring',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False, unique=True)),
                ('red', models.BooleanField(default=False)),
                ('mobility', models.IntegerField(default=0)),
                ('grid', models.IntegerField(default=0)),
                ('charge', models.IntegerField(default=0)),
                ('penalty', models.IntegerField(default=0)),
                ('total', models.IntegerField(default=0)),
                ('rank', models.IntegerField(default=0)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sysScore', to='index.match')),
                ('team', models.ManyToManyField(related_name='sysScore', to='index.team')),
            ],
        ),
        migrations.CreateModel(
            name='SuperScout',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False, unique=True)),
                ('scouter', models.CharField(default='', max_length=30)),
                ('quick', models.IntegerField(default=3)),
                ('defence', models.IntegerField(default=3)),
                ('aware', models.IntegerField(default=3)),
                ('human', models.IntegerField(default=3)),
                ('pick', models.IntegerField(default=3)),
                ('place', models.IntegerField(default=3)),
                ('foul', models.CharField(default='', max_length=100)),
                ('other', models.CharField(default='', max_length=100)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scouts', to='index.match')),
                ('team', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scouts', to='index.team')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='MatchData',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False, unique=True)),
                ('team', models.IntegerField(default=0)),
                ('scouter', models.CharField(default='', max_length=30)),
                ('robot', models.IntegerField(default=0)),
                ('start', models.IntegerField(default=0)),
                ('auto_grid', models.TextField(default='')),
                ('tele_grid', models.TextField(default='')),
                ('cross_cable', models.BooleanField(default=False)),
                ('cross_charge', models.BooleanField(default=False)),
                ('auto_mobility', models.BooleanField(default=False)),
                ('auto_dock', models.IntegerField(default=0)),
                ('timer_cycle', models.TextField(default='')),
                ('tele_trans', models.IntegerField(default=0)),
                ('tele_fed', models.BooleanField(default=False)),
                ('tele_defender', models.CharField(default='', max_length=15)),
                ('tele_pick_fn', models.IntegerField(default=0)),
                ('tele_pick_fb', models.IntegerField(default=0)),
                ('tele_pick_sn', models.IntegerField(default=0)),
                ('tele_pick_sb', models.IntegerField(default=0)),
                ('tele_fail', models.IntegerField(default=0)),
                ('timer_dock', models.TextField(default='')),
                ('end_dock', models.IntegerField(default=0)),
                ('other_link', models.TextField(default='')),
                ('other_immobolity', models.BooleanField(default=False)),
                ('other_tippy', models.BooleanField(default=False)),
                ('other_comment', models.TextField(default='')),
                ('score_auto', models.IntegerField(default=0)),
                ('score_tele', models.IntegerField(default=0)),
                ('score_link', models.IntegerField(default=0)),
                ('score_dock', models.IntegerField(default=0)),
                ('score_grid', models.IntegerField(default=0)),
                ('score_total', models.IntegerField(default=0)),
                ('score_opr', models.FloatField(default=0)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='index.match')),
                ('team_data', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scores', to='index.team')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
