# Generated by Django 4.1.7 on 2023-03-02 04:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(default=0)),
                ('num', models.IntegerField(default=0)),
                ('teams', models.TextField(default='')),
            ],
        ),
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(default='', max_length=63),
        ),
        migrations.CreateModel(
            name='SuperScout',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False, unique=True)),
                ('quick', models.IntegerField()),
                ('defence', models.IntegerField()),
                ('aware', models.IntegerField()),
                ('human', models.IntegerField()),
                ('pick', models.IntegerField()),
                ('place', models.IntegerField()),
                ('foul', models.IntegerField()),
                ('other', models.CharField(max_length=100)),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.match')),
            ],
        ),
        migrations.CreateModel(
            name='MatchData',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False, unique=True)),
                ('scouter', models.CharField(default='', max_length=30)),
                ('robot', models.IntegerField(default=0)),
                ('start', models.IntegerField(default=0)),
                ('auto_score', models.TextField(default='')),
                ('tele_score', models.TextField(default='')),
                ('cross_cable', models.BooleanField(default=False)),
                ('cross_charge', models.BooleanField(default=False)),
                ('auto_mobility', models.BooleanField(default=False)),
                ('auto_docked', models.IntegerField(default=0)),
                ('timer_cycle', models.TextField(default='')),
                ('tele_trans', models.IntegerField(default=0)),
                ('tele_fed', models.IntegerField(default=0)),
                ('tele_defended', models.BooleanField(default=False)),
                ('tele_defender', models.CharField(default='', max_length=15)),
                ('tele_pick', models.IntegerField(default=0)),
                ('tele_fail', models.IntegerField(default=0)),
                ('timer_dock', models.TextField(default='')),
                ('end_dock', models.IntegerField(default=0)),
                ('other_link', models.IntegerField(default=0)),
                ('other_immobolity', models.BooleanField(default=False)),
                ('other_comment', models.TextField(default='')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.match')),
            ],
        ),
        migrations.AddField(
            model_name='match',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.event'),
        ),
    ]
