# Generated by Django 4.1.7 on 2023-03-02 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_match_alter_event_name_superscout_matchdata_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='week',
            field=models.IntegerField(default=1),
        ),
    ]
