# Generated by Django 4.1.7 on 2023-04-11 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_alter_matchdata_options_alter_superscout_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchdata',
            name='auto_grid',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='matchdata',
            name='other_comment',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='matchdata',
            name='other_link',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='matchdata',
            name='scouter',
            field=models.CharField(blank=True, default='', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='matchdata',
            name='team_data',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scores', to='index.team'),
        ),
        migrations.AlterField(
            model_name='matchdata',
            name='tele_defender',
            field=models.CharField(blank=True, default='', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='matchdata',
            name='tele_grid',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='matchdata',
            name='timer_cycle',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='matchdata',
            name='timer_dock',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='superscout',
            name='comment',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='superscout',
            name='foul',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='superscout',
            name='scouter',
            field=models.CharField(blank=True, default='', max_length=30, null=True),
        ),
    ]
