# Generated by Django 4.1.7 on 2023-03-02 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_event_week'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['week', 'id']},
        ),
        migrations.AlterField(
            model_name='match',
            name='id',
            field=models.CharField(max_length=30, primary_key=True, serialize=False, unique=True),
        ),
    ]
