# Generated by Django 4.1.7 on 2023-03-03 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_alter_event_options_alter_match_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='matchdata',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='superscout',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='match',
            name='score_blue',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='score_red',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='superscout',
            name='aware',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='superscout',
            name='defence',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='superscout',
            name='foul',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='superscout',
            name='human',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='superscout',
            name='other',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='superscout',
            name='pick',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='superscout',
            name='place',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='superscout',
            name='quick',
            field=models.IntegerField(default=3),
        ),
    ]
