# Generated by Django 4.1.7 on 2023-03-03 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_alter_matchdata_options_alter_superscout_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='superscout',
            name='foul',
            field=models.CharField(default='', max_length=100),
        ),
    ]
