# Generated by Django 4.1.7 on 2023-03-03 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0006_alter_superscout_foul'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchdata',
            name='team',
            field=models.IntegerField(default=0),
        ),
    ]
