# Generated by Django 4.1.7 on 2023-03-06 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0007_matchdata_team'),
    ]

    operations = [
        migrations.RenameField(
            model_name='matchdata',
            old_name='tele_defended',
            new_name='other_tippy',
        ),
        migrations.AlterField(
            model_name='matchdata',
            name='tele_fed',
            field=models.BooleanField(default=False),
        ),
    ]
