# Generated by Django 4.1.7 on 2023-03-07 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0009_rename_target_matchdata_match_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchdata',
            name='tele_pick',
            field=models.CharField(default='0000', max_length=4),
        ),
    ]
