# Generated by Django 4.1.7 on 2023-03-19 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0011_systemscoring'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchdata',
            name='score_auto',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='matchdata',
            name='score_link',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='matchdata',
            name='score_tele',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='matchdata',
            name='score_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='systemscoring',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sysScore', to='index.match'),
        ),
    ]
