# Generated by Django 4.1.7 on 2023-03-19 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0012_matchdata_score_auto_matchdata_score_link_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='matchdata',
            old_name='score_auto',
            new_name='score_dock',
        ),
        migrations.RenameField(
            model_name='matchdata',
            old_name='score_tele',
            new_name='score_grid',
        ),
        migrations.AlterField(
            model_name='matchdata',
            name='other_link',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='matchdata',
            name='score_link',
            field=models.IntegerField(default=0),
        ),
    ]
