# Generated by Django 4.1.7 on 2023-03-20 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0013_rename_score_auto_matchdata_score_dock_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matchdata',
            name='tele_pick',
        ),
        migrations.AddField(
            model_name='matchdata',
            name='tele_pick_fb',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='matchdata',
            name='tele_pick_fn',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='matchdata',
            name='tele_pick_sb',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='matchdata',
            name='tele_pick_sn',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='match',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='index.event'),
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False, unique=True)),
                ('num', models.IntegerField(default=0)),
                ('score_highest', models.IntegerField(default=0)),
                ('score_rank', models.IntegerField(default=0)),
                ('score_opr', models.IntegerField(default=0)),
                ('auto_start', models.IntegerField(default=0)),
                ('auto_hihgest', models.IntegerField(default=0)),
                ('auto_dock', models.IntegerField(default=0)),
                ('auto_engage', models.IntegerField(default=0)),
                ('tele_highest', models.IntegerField(default=0)),
                ('tele_pick', models.IntegerField(default=0)),
                ('tele_top', models.IntegerField(default=0)),
                ('tele_mid', models.IntegerField(default=0)),
                ('tele_bot', models.IntegerField(default=0)),
                ('tele_cycle', models.FloatField(default=0)),
                ('tele_dock_time', models.FloatField(default=0)),
                ('tele_enga_time', models.FloatField(default=0)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.event')),
            ],
        ),
    ]
