# Generated by Django 4.1.7 on 2023-03-20 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0014_remove_matchdata_tele_pick_matchdata_tele_pick_fb_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchdata',
            name='team_data',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='index.team'),
        ),
    ]
