# Generated by Django 4.1.7 on 2023-03-20 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0015_matchdata_team_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchdata',
            name='team_data',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='index.team'),
        ),
    ]
