# Generated by Django 4.1.7 on 2023-03-20 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0016_alter_matchdata_team_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='superscout',
            name='scouter',
            field=models.CharField(default='', max_length=30),
        ),
    ]
