# Generated by Django 4.1.7 on 2023-03-23 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0017_superscout_scouter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='tele_dock_time',
            new_name='auto_avg',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='auto_hihgest',
            new_name='auto_bot',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='score_highest',
            new_name='auto_max',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='tele_highest',
            new_name='auto_mid',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='tele_enga_time',
            new_name='end_dock_time',
        ),
        migrations.AddField(
            model_name='superscout',
            name='team',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scouts', to='index.team'),
        ),
        migrations.AddField(
            model_name='team',
            name='auto_top',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='end_dock',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='end_engage',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='score_avg',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='score_max',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='tele_avg',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='tele_max',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='tele_src',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='tele_success',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='matchdata',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='index.match'),
        ),
        migrations.AlterField(
            model_name='matchdata',
            name='team_data',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scores', to='index.team'),
        ),
        migrations.AlterField(
            model_name='superscout',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scouts', to='index.match'),
        ),
    ]
