# Generated by Django 4.1.7 on 2023-03-23 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0018_rename_tele_dock_time_team_auto_avg_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchdata',
            name='score_auto',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='matchdata',
            name='score_tele',
            field=models.IntegerField(default=0),
        ),
    ]
