# Generated by Django 4.1.7 on 2023-03-23 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0019_matchdata_score_auto_matchdata_score_tele'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='name',
            field=models.CharField(default='', max_length=60),
        ),
    ]
