# Generated by Django 4.1.7 on 2023-03-23 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0020_team_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='score_blue',
        ),
        migrations.RemoveField(
            model_name='match',
            name='score_red',
        ),
    ]
