# Generated by Django 4.1.7 on 2023-03-24 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0021_remove_match_score_blue_remove_match_score_red'),
    ]

    operations = [
        migrations.RenameField(
            model_name='matchdata',
            old_name='auto_docked',
            new_name='auto_dock',
        ),
        migrations.RemoveField(
            model_name='team',
            name='auto_avg',
        ),
        migrations.RemoveField(
            model_name='team',
            name='auto_bot',
        ),
        migrations.RemoveField(
            model_name='team',
            name='auto_dock',
        ),
        migrations.RemoveField(
            model_name='team',
            name='auto_engage',
        ),
        migrations.RemoveField(
            model_name='team',
            name='auto_max',
        ),
        migrations.RemoveField(
            model_name='team',
            name='auto_mid',
        ),
        migrations.RemoveField(
            model_name='team',
            name='auto_start',
        ),
        migrations.RemoveField(
            model_name='team',
            name='auto_top',
        ),
        migrations.RemoveField(
            model_name='team',
            name='end_dock',
        ),
        migrations.RemoveField(
            model_name='team',
            name='end_dock_time',
        ),
        migrations.RemoveField(
            model_name='team',
            name='end_engage',
        ),
        migrations.RemoveField(
            model_name='team',
            name='score_avg',
        ),
        migrations.RemoveField(
            model_name='team',
            name='score_max',
        ),
        migrations.RemoveField(
            model_name='team',
            name='score_opr',
        ),
        migrations.RemoveField(
            model_name='team',
            name='score_rank',
        ),
        migrations.RemoveField(
            model_name='team',
            name='tele_avg',
        ),
        migrations.RemoveField(
            model_name='team',
            name='tele_bot',
        ),
        migrations.RemoveField(
            model_name='team',
            name='tele_cycle',
        ),
        migrations.RemoveField(
            model_name='team',
            name='tele_max',
        ),
        migrations.RemoveField(
            model_name='team',
            name='tele_mid',
        ),
        migrations.RemoveField(
            model_name='team',
            name='tele_pick',
        ),
        migrations.RemoveField(
            model_name='team',
            name='tele_src',
        ),
        migrations.RemoveField(
            model_name='team',
            name='tele_success',
        ),
        migrations.RemoveField(
            model_name='team',
            name='tele_top',
        ),
        migrations.AddField(
            model_name='systemscoring',
            name='team',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sysScore', to='index.team'),
        ),
    ]
