# Generated by Django 4.1.7 on 2023-03-24 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0022_rename_auto_docked_matchdata_auto_dock_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemscoring',
            name='team',
        ),
        migrations.AddField(
            model_name='systemscoring',
            name='team',
            field=models.ManyToManyField(related_name='sysScore', to='index.team'),
        ),
    ]
