# Generated by Django 4.1.7 on 2023-03-24 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0023_remove_systemscoring_team_systemscoring_team'),
    ]

    operations = [
        migrations.RenameField(
            model_name='matchdata',
            old_name='auto_score',
            new_name='auto_grid',
        ),
        migrations.RenameField(
            model_name='matchdata',
            old_name='tele_score',
            new_name='tele_grid',
        ),
    ]
